CREATE TABLE IF NOT EXISTS "guest_book" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" text NOT NULL,
    "message" text NOT NULL,
    "createdAt" timestamptz DEFAULT now(),
    CONSTRAINT "guest_book_pk" PRIMARY KEY ("id")
);
